3cef1ba3-a63a-4123-b032-c91800c40388:
  uuid: 3cef1ba3-a63a-4123-b032-c91800c40388
  title: 'McGaw Landing Pages'
  source: 'https://openy-mcgawymca.y.org/jsonapi/node/landing_page'
  type: landing_page
