_core:
  default_config_hash: 6pu-bqSEHFbUWhCoPxMom5frvldpqvdyoODAVKiIF6k
included_entities: 'block_content,file,node,taxonomy_term'
included_bundles: 'block_content:basic,file:file,node:article,node:page,taxonomy_term:tags'
